export const cities = [
    'Madrid',
    'Paris',
    'London',
    'New York',
    'Tokyo',
    'Berlin',
    'Rome',
    'Sydney',
    'Moscow',
    'Beijing',
    'Toronto',
    'Dubai',
    'Cairo',
    'Rio de Janeiro',
    'Singapore',
    'Seoul',
    'Mumbai',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Shanghai',
    'Istanbul',
    'Jakarta',
    'Bangkok',
    'Amsterdam',
    'Vienna',
    'Athens',
    'Stockholm',
    'Copenhagen',
    'Dublin',
    'Lisbon',
    'Warsaw',
    'Prague',
    'Budapest',
    'Barcelona',
    'Milan',
    'Oslo',
    'Helsinki',
    'Brussels',
    'Zurich',
    'Geneva',
    'Luxembourg City',
    'Monaco',
    'Montreal',
    'Vancouver',
    'Wellington',
    'Auckland',
    'Cape Town',
    'Johannesburg',
    'Lagos',
    'Nairobi',
    'Marrakech',
    'Kuala Lumpur',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Christchurch',
    'Queenstown',
    'Rotorua',
    'Osaka',
    'Kyoto',
    'Nara',
    'Hiroshima',
    'Fukuoka',
    'Sapporo',
    'Nagoya',
    'Kobe',
    'Yokohama',
    'Sendai',
    'Penang',
    'Malacca',
    'Ipoh',
    'Johor Bahru',
    'Langkawi',
    'Kota Kinabalu',
    'Kuching',
    'Buenos Aires',
    'Lima',
    'Bandar Seri Begawan',
    'Ho Chi Minh City',
    'Hanoi',
    'Da Nang',
    'Nha Trang',
    'Hue',
    'Hoi An',
    'Phnom Penh',
    'Siem Reap',
    'Sihanoukville',
    'Vientiane',
    'Luang Prabang',
    'Yangon',
    'Mandalay',
    'Bagan',
    'Inle Lake',
    'Battambang',
    'Phuket',
    'Pattaya',
    'Chiang Mai',
    'Koh Samui',
    'Krabi',
    'Phi Phi Islands',
    'Hua Hin',
    'Ayutthaya',
    'Kanchanaburi',
    'Chiang Rai',
    'Mae Hong Son',
    'Sukhothai',
    'Surat Thani',
    'Ko Tao',
    'Ko Pha Ngan',
    'Ko Lanta',
    'Ko Phi Phi',
    'Ko Samet',
    'Ko Chang',
    'Ko Kut',
    'Ko Lipe',
    'Ko Tarutao',
    'Khao Lak',
    'Khao Sok National Park',
    'Trang',
    'Ao Nang',
    'Phang Nga Bay',
    'Similan Islands',
    'Ko Yao',
    'Ko Ngai',
    'Ko Yao Noi',
    'Ko Yao Yai',
    'Mexico City',
    'Santiago',
    'Bogota',
    'Sao Paulo',
    'Caracas',
    'Guatemala City',
    'San Salvador',
    'Panama City',
    'Asuncion',
    'San Jose',
    'Tegucigalpa',
    'Managua',
    'Havana',
    'Nassau',
    'Kingston',
    'Port-au-Prince',
    'Santo Domingo',
    'Bridgetown',
    'Port of Spain',
    'Georgetown',
    'Paramaribo',
    'Cayenne',
    'Belmopan',
    'Roseau',
    'Castries',
    'St. John\'s',
    'Basseterre',
    'Kingstown',
    'Port Moresby',
    'Sucre',
    'Brasilia',
    'Belém',
    'Salvador',
    'Fortaleza',
    'Recife',
    'João Pessoa',
    'Natal',
    'Aracaju',
    'Maceió',
    'Teresina',
    'São Luís',
    'Cuiabá',
    'Campo Grande',
    'Palmas',
    'Goiânia',
    'Porto Velho',
    'Manaus',
    'Boa Vista',
    'Macapá',
    'Santarém',
    'Rio Branco'
];